### ISSUE TITLE
Removing TreeSitter?

### ISSUE THREAD

**Issue by blissdev** [icyphox/dotfiles#4]
Hi, as someone who's in the process of setting up a modern neovim config, I was curious why you removed treesitter. Are you encountering bugginess? Or are there other reasons?

Thanks.

**Comment by icyphox** [comment]
Jordan Arentsen ***@***.***> wrote:

> Hi, as someone who's in the process of setting up a modern neovim
> config, I was curious why you removed treesitter. Are you encountering
> bugginess? Or are there other reasons?
> 
> Thanks.
> 
> -- You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/icyphox/dotfiles/issues/4

It isn't buggy per se, but it's certainly pretty janky (and does break
very rarely). Syntax highlighting changes as you type -- which is
expected behaviour, but super jarring; the indents are weird / not what
I'd like, etc. It's probably just not for me, but you can try it and see
if you like it, takes very little effort to get it set up.

--
Anirudh Oppiliappan
https://icyphox.sh
